'use client';

import { useMemo, useState } from 'react';
import AuthBar from '@/components/auth-bar';
import QualityBadge from './quality-badge';
import './quality.css';

type Mode = 'custom'|'leads'|'trends'|'opportunities'|'tenders'|'ecommerce'|'competitors'|'outreach'|'content';
type Config = { label:string; title:string; question:string; placeholder:string; fields:string[]; build:(answer:string, fields:Record<string,string>)=>string };
type AnyResult = { plan?:{explanation?:string;agents?:string[]}; outputs?:Array<{agent?:string;result?:any}>; error?:string };

const MODES:Record<Mode,Config>={
 custom:{label:'Anything',title:'Tell Victory AI what you want done',question:'What do you want me to do?',placeholder:'Example: Find what is trending on Reddit, identify the best business opportunities, then find real businesses I can contact.',fields:[],build:a=>a},
 leads:{label:'Find leads',title:'Find business leads',question:'What kind of businesses or customers should I find?',placeholder:'Example: restaurants in Lagos that need better websites',fields:['Location','Industry','How many leads?'],build:(a,f)=>`Find ${f['How many leads?']||'10'} good business leads for: ${a}. Location: ${f.Location||'anywhere'}. Industry: ${f.Industry||'any'}.`},
 trends:{label:'Find trends',title:'Discover what is trending',question:'What market, topic, product or niche should I investigate?',placeholder:'Example: AI products and business ideas that are trending now',fields:['Market/location','Time window'],build:(a,f)=>`Find current trends for ${a}. Market/location: ${f['Market/location']||'global'}. Time window: ${f['Time window']||'recent'}. Use Reddit and other source-backed sources.`},
 opportunities:{label:'Find opportunities',title:'Turn demand into opportunities',question:'What business idea, problem or market should I turn into opportunities?',placeholder:'Example: problems people complain about that businesses can pay to solve',fields:['Target market','Budget'],build:(a,f)=>`Find actionable business opportunities around ${a}. Target market: ${f['Target market']||'global'}. Budget: ${f.Budget||'not specified'}.`},
 tenders:{label:'Find tenders',title:'Find procurement opportunities',question:'What type of contract or procurement opportunity should I find?',placeholder:'Example: software and cybersecurity contracts',fields:['Country/region','Deadline'],build:(a,f)=>`Find relevant public tenders/contracts for ${a}. Country/region: ${f['Country/region']||'global'}. Deadline: ${f.Deadline||'open'}.`},
 ecommerce:{label:'Find products',title:'Find ecommerce opportunities',question:'What product category or customer problem should I investigate?',placeholder:'Example: products people ask for on Reddit but cannot find easily',fields:['Target market','Price range'],build:(a,f)=>`Find ecommerce opportunities for ${a}. Target market: ${f['Target market']||'global'}. Price range: ${f['Price range']||'any'}.`},
 competitors:{label:'Monitor competitors',title:'Monitor competitor changes',question:'Which competitors, websites or market should I monitor?',placeholder:'Example: competitors to my web design agency',fields:['Industry','Alert focus'],build:(a,f)=>`Monitor public competitor changes for ${a}. Industry: ${f.Industry||'any'}. Alert focus: ${f['Alert focus']||'important changes'}.`},
 outreach:{label:'Create outreach',title:'Prepare personalized outreach',question:'Who are you trying to reach and what are you offering?',placeholder:'Example: restaurants that need online ordering',fields:['Offer','Tone'],build:(a,f)=>`Create approval-first personalized outreach for ${a}. Offer: ${f.Offer||'not specified'}. Tone: ${f.Tone||'professional'}.`},
 content:{label:'Create content',title:'Create business content',question:'What business, product or topic should I create content for?',placeholder:'Example: AI lead generation for small businesses',fields:['Audience','Content type'],build:(a,f)=>`Create practical business content about ${a}. Audience: ${f.Audience||'business owners'}. Content type: ${f['Content type']||'social posts and blog ideas'}`}
};

function recordsOf(result:any){
 const found:any[]=[];
 const walk=(v:any)=>{if(v==null)return;if(Array.isArray(v)){v.forEach(walk);return}if(typeof v==='object'){if(Array.isArray(v.results))v.results.forEach((x:any)=>found.push(x));Object.entries(v).forEach(([k,x])=>{if(k!=='results'&&typeof x==='object')walk(x)})}};
 walk(result); return found;
}
function scoreOf(item:any){return typeof item?.score==='number'?item.score:undefined}
function sourceOf(item:any){return item?.url||item?.sourceUrl||item?.website||item?.link||item?.source?.url}
function titleOf(item:any){return item?.business?.name||item?.company||item?.name||item?.title||item?.businessName||'Opportunity'}
function detailOf(item:any){return item?.description||item?.summary||item?.business?.industry||item?.industry||item?.category||item?.type||'Source-backed result'}
function locationOf(item:any){const x=item?.location||item?.business?.location;if(typeof x==='string')return x;if(x?.name)return x.name;return [item?.city,item?.country,item?.business?.city,item?.business?.country].filter(Boolean).join(', ')}
function messageOf(result:any){return result?.message||result?.status||result?.error||result?.warnings?.[0]||'Agent completed without a displayable record.'}

export default function CommandDashboard(){
 const [mode,setMode]=useState<Mode>('custom');const [answer,setAnswer]=useState('');const [fields,setFields]=useState<Record<string,string>>({});const [busy,setBusy]=useState(false);const [result,setResult]=useState<AnyResult|null>(null);const [error,setError]=useState('');
 const config=MODES[mode];const command=useMemo(()=>config.build(answer,fields),[config,answer,fields]);
 const allRecords=useMemo(()=>result?.outputs?.flatMap(o=>recordsOf(o.result))||[],[result]);
 function choose(m:Mode){setMode(m);setAnswer('');setFields({});setResult(null);setError('')}
 async function submit(e:React.FormEvent){e.preventDefault();if(!answer.trim()||busy)return;setBusy(true);setError('');setResult(null);try{const r=await fetch('/api/command-agent',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({command,limit:25})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Command failed');setResult(d)}catch(x){setError(x instanceof Error?x.message:'Command failed')}finally{setBusy(false)}}
 return <div className="command-dashboard">
  <header className="cd-top"><div className="cd-brand"><span>VA</span><strong>Victory <b>AI</b></strong></div><div className="cd-account"><AuthBar onTokenChange={()=>{}}/></div></header>
  <main className="cd-main">
   <section className="cd-hero"><div><p className="cd-kicker">YOUR AI WORKSPACE</p><h1>What do you want<br/><em>Victory AI</em> to do?</h1><p>Describe the outcome in normal language. Victory AI chooses the right agents, combines them when needed, researches multiple sources, scores evidence and presents the useful information as results.</p></div><div className="cd-status"><strong>9 AI AGENTS</strong><span>understand → research → verify → score → act</span></div></section>
   <section className="cd-card"><div className="cd-card-head"><div><p className="cd-kicker">SMART COMMAND</p><h2>{config.title}</h2><span>{config.question}</span></div><div className="legend"><span className="good">● GOOD</span><span className="medium">● MEDIUM</span><span className="bad">● BAD</span></div></div>
    <div className="cd-modes">{(Object.keys(MODES) as Mode[]).map(m=><button key={m} type="button" className={m===mode?'active':''} onClick={()=>choose(m)}>{MODES[m].label}</button>)}</div>
    <div className="cd-hint">You can ignore the buttons and type exactly what you want. Compound requests can use several agents automatically.</div>
    <form onSubmit={submit} className="cd-form"><label>{config.question}<textarea value={answer} onChange={e=>setAnswer(e.target.value)} placeholder={config.placeholder} rows={4} required/></label>{config.fields.map(f=><label key={f}>{f}<input value={fields[f]||''} onChange={e=>setFields(v=>({...v,[f]:e.target.value}))} placeholder={`Enter ${f.toLowerCase()}`}/></label>)}<div className="cd-preview"><small>COMMAND PREVIEW</small><div>{command||'Your command will appear here.'}</div></div><button className="cd-run" disabled={busy||!answer.trim()}>{busy?'Working across the selected agents…':'Run job →'}</button></form>{error&&<div className="cd-error">{error}</div>}
   </section>
   {result&&<section className="cd-results"><div className="cd-result-head"><div><p className="cd-kicker">JOB RESULT</p><h2>{result.plan?.explanation||'Job completed'}</h2><p className="result-note">{result.outputs?.length||0} agent(s) were used. Results below are rendered as readable evidence, not raw system data.</p></div><div className="agents-used">{result.plan?.agents?.map(a=><span key={a}>{a}</span>)}</div></div>
    {allRecords.length>0&&<div className="result-stats"><b>{allRecords.length}</b><span>results found</span><span className="good">● Good</span><span className="medium">● Medium</span><span className="bad">● Bad</span></div>}
    {allRecords.length>0&&<div className="cd-records">{allRecords.map((item:any,i:number)=>{const score=scoreOf(item);const src=sourceOf(item);const name=titleOf(item);return <article key={item.id||`${name}-${i}`}><div className="record-main"><strong>{name}</strong><small>{detailOf(item)}</small>{locationOf(item)&&<small>📍 {locationOf(item)}</small>}{(item.email||item.business?.email)&&<small>✉ {item.email||item.business.email}</small>}{(item.phone||item.business?.phone)&&<small>☎ {item.phone||item.business.phone}</small>}{src&&<a href={src} target="_blank" rel="noreferrer">View source ↗</a>}</div><div className="score-wrap">{score!==undefined?<><QualityBadge score={score}/><b>{score}/100</b></>:<span className="unrated">UNRATED</span>}</div></article>})}</div>}
    <div className="agent-results">{result.outputs?.map((o,i)=>{const rs=recordsOf(o.result);const r=o.result||{};return <article className="agent-result" key={`${o.agent}-${i}`}><div className="agent-result-head"><strong>{o.agent||'Agent'}</strong><span>{rs.length} results</span></div>{rs.length===0?<div className="agent-status"><strong>{r?.error?'Needs attention':'No source-backed records returned'}</strong><p>{messageOf(r)}</p>{Array.isArray(r?.warnings)&&r.warnings.length>0&&<ul>{r.warnings.map((w:string,j:number)=><li key={j}>{w}</li>)}</ul>}</div>:<div className="agent-status success"><strong>{rs.length} readable result{rs.length===1?'':'s'} found</strong><p>The useful records are shown above. Open a source to verify the original evidence.</p></div>}</article>})}</div>
   </section>}
  </main><footer className="cd-footer">Victory AI · evidence-aware multi-agent business intelligence</footer>
  <style jsx>{`
   .command-dashboard{position:fixed;inset:0;z-index:9998;overflow:auto;background:#06101b;color:#eaf2f8;font-family:Inter,system-ui,sans-serif}
   .cd-top{min-height:68px;padding:0 28px;display:flex;align-items:center;justify-content:space-between;gap:18px;border-bottom:1px solid #1d3040;background:#07131f;position:sticky;top:0;z-index:10}.cd-brand{display:flex;align-items:center;gap:10px;font-size:20px;white-space:nowrap}.cd-brand>span{display:grid;place-items:center;width:38px;height:38px;border-radius:11px;background:#123c3a;color:#7ee7c4;font-size:11px}.cd-brand b,.cd-hero em{color:#7ee7c4;font-style:normal}.cd-account{display:flex;justify-content:flex-end;min-width:0}
   .cd-main{max-width:1120px;margin:auto;padding:34px 24px}.cd-hero{display:flex;justify-content:space-between;align-items:end;gap:30px;padding:34px 0}.cd-kicker{margin:0 0 8px;color:#6dd8b5;font-size:10px;font-weight:800;letter-spacing:.16em}.cd-hero h1{font-size:clamp(42px,7vw,72px);line-height:.96;letter-spacing:-.05em;margin:0}.cd-hero>div:first-child p:last-child{max-width:700px;color:#91a6b6;line-height:1.6}.cd-status{min-width:210px;padding:20px;border:1px solid #243a4b;border-radius:16px;background:#0b1824;display:flex;flex-direction:column;gap:7px}.cd-status span{font-size:11px;color:#7d94a5;line-height:1.4}
   .cd-card,.cd-results{border:1px solid #274052;border-radius:20px;background:#0b1824;padding:24px;box-shadow:0 15px 45px rgba(0,0,0,.18)}.cd-card-head,.cd-result-head{display:flex;justify-content:space-between;gap:20px;align-items:flex-start}.cd-card h2,.cd-results h2{margin:0 0 6px;font-size:25px}.cd-card-head>div:first-child>span{color:#8ea3b3;font-size:13px}.legend{display:flex;gap:10px;font-size:9px;letter-spacing:.08em}.good{color:#58e0aa}.medium{color:#e8cc55}.bad{color:#ff6975}
   .cd-modes{display:flex;gap:8px;flex-wrap:wrap;margin:20px 0 10px}.cd-modes button{border:1px solid #2b4557;background:#0f2431;color:#a9e7d6;border-radius:999px;padding:9px 12px;font-size:11px;cursor:pointer}.cd-modes button.active{background:#74dfbd;color:#06140f;border-color:#74dfbd;font-weight:800}.cd-hint{color:#6f8799;font-size:10px;line-height:1.5;margin-bottom:14px}
   .cd-form{display:grid;grid-template-columns:repeat(2,1fr);gap:12px}.cd-form label{display:grid;gap:7px;color:#8ea3b3;font-size:10px}.cd-form label:first-child{grid-column:1/-1}.cd-form textarea,.cd-form input{width:100%;box-sizing:border-box;background:#07121b;color:#e8f3f7;border:1px solid #2a4655;border-radius:10px;padding:13px;font:inherit;outline:none}.cd-form textarea{resize:vertical}.cd-preview{grid-column:1/-1;border:1px solid #243b4b;border-radius:10px;background:#08141e;padding:12px}.cd-preview small{color:#6dd8b5;font-size:8px;letter-spacing:.14em}.cd-preview div{margin-top:6px;color:#c0d0d9;font-size:12px;line-height:1.45}.cd-run{grid-column:1/-1;height:50px;border:0;border-radius:10px;background:#74dfbd;color:#06140f;font-weight:900;cursor:pointer}.cd-run:disabled{opacity:.5}.cd-error{margin-top:12px;color:#ff9da5}
   .cd-results{margin-top:22px}.result-note{color:#7e94a5;font-size:11px;line-height:1.5}.agents-used{display:flex;gap:6px;flex-wrap:wrap}.agents-used span{padding:5px 8px;border-radius:999px;background:#17323d;color:#9fe5d3;font-size:9px}.result-stats{display:flex;gap:12px;align-items:center;flex-wrap:wrap;margin:18px 0 10px;padding:10px 12px;border:1px solid #203748;border-radius:10px;color:#8298a8;font-size:10px}.result-stats b{color:#eaf2f8;font-size:15px}
   .cd-records{display:grid;gap:9px}.cd-records article{display:flex;justify-content:space-between;gap:15px;align-items:center;border:1px solid #223a4b;border-radius:12px;background:#091621;padding:14px}.record-main{display:grid;gap:5px;min-width:0}.record-main strong{font-size:15px}.record-main small{color:#8197a8;font-size:10px;line-height:1.4}.record-main a{color:#75dfc0;font-size:10px;text-decoration:none}.score-wrap{display:flex;align-items:center;gap:8px;flex:0 0 auto}.score-wrap b{font-size:10px;color:#a9bac5}.unrated{font-size:8px;color:#8197a8;border:1px solid #334b5c;border-radius:999px;padding:5px 7px}
   .agent-results{display:grid;gap:9px;margin-top:16px}.agent-result{border:1px solid #223a4b;border-radius:12px;background:#091621;overflow:hidden}.agent-result-head{display:flex;justify-content:space-between;padding:12px 14px;border-bottom:1px solid #203748}.agent-result-head strong{color:#9fe5d3;font-size:12px}.agent-result-head span{color:#71899b;font-size:9px}.agent-status{padding:13px 14px}.agent-status strong{font-size:11px}.agent-status p{color:#8197a8;font-size:10px;line-height:1.5;margin:5px 0 0}.agent-status ul{color:#8197a8;font-size:10px;line-height:1.6;margin:7px 0 0;padding-left:18px}.agent-status.success{background:#0b211b}.cd-footer{text-align:center;padding:30px 20px;color:#61798c;font-size:10px}
   @media(max-width:800px){.cd-top{padding:12px 16px;align-items:flex-start}.cd-account{max-width:62%}.cd-main{padding:22px 14px}.cd-hero{display:block;padding:25px 0}.cd-status{margin-top:18px;min-width:0}.cd-card,.cd-results{padding:17px}.cd-card-head,.cd-result-head{display:block}.legend{margin-top:12px}.cd-form{grid-template-columns:1fr}.cd-form label:first-child{grid-column:auto}.cd-preview,.cd-run{grid-column:auto}.cd-records article{align-items:flex-start}.score-wrap{flex-direction:column}}
   @media(max-width:500px){.cd-top{position:relative;flex-direction:column}.cd-account{max-width:100%;width:100%;justify-content:stretch}.cd-hero h1{font-size:42px}.cd-modes button{padding:8px 10px}.cd-records article{display:block}.score-wrap{margin-top:10px;flex-direction:row}.cd-results h2{font-size:20px}}
  `}</style>
 </div>;
}
