'use client';
import { FormEvent, useState } from 'react';
import { searchLeadFinder, searchTrendLeads } from '../../src/api/lead-finder-client';
import { researchQuestion, type ResearchResponse } from '../../src/api/research-client';
import LeadQualityBadge from '../../components/lead-quality-badge';
import BusinessLink from '../../components/business-link';

type Lead={lead?:{id?:string;score?:number;scoreLabel?:string};business?:{name?:string;website?:string;phone?:string;email?:string;address?:string;city?:string;country?:string;industry?:string;source?:string};report?:{confidence?:number;level?:string;recommendation?:string}};
type Trend={title:string;source:string;url?:string;community?:string;relevance:number};type SearchResult={results?:Lead[];count?:number;warnings?:string[];error?:string;trends?:Trend[];strategy?:string[]};type SmartResearch=ResearchResponse & {insights?:Array<{type:string;text:string;confidence:number}>;sources?:Array<{title:string;url:string;source:string;snippet?:string;evidenceScore?:number}>};
function interpretPrompt(prompt:string){const text=prompt.trim();const lower=text.toLowerCase();const countries=['nigeria','ghana','kenya','south africa','united states','usa','canada','uk','united kingdom','india','australia','germany','france','uae'];const country=countries.find(x=>lower.includes(x))??'';const cities=['lagos','abuja','port harcourt','ibadan','benin city','kano'];const city=cities.find(x=>lower.includes(x))??'';return {industry:'',country,city,keywords:text};}
export default function LeadFinderPage(){const [prompt,setPrompt]=useState('');const [filters,setFilters]=useState({industry:'',country:'',city:'',keywords:'',limit:25});const [trendMode,setTrendMode]=useState(true);const [result,setResult]=useState<SearchResult>({});const [research,setResearch]=useState<SmartResearch>({});const [loading,setLoading]=useState(false);const [researching,setResearching]=useState(false);
 async function submit(e:FormEvent){e.preventDefault();const next={...filters,...interpretPrompt(prompt||filters.keywords)};setFilters(next);setLoading(true);try{const body=trendMode?await searchTrendLeads(next):await searchLeadFinder(next);setResult(body as SearchResult)}catch(error){setResult({error:error instanceof Error?error.message:'Search failed'})}finally{setLoading(false)}}
 async function researchNow(){if(!prompt.trim())return;setResearching(true);setResearch({});try{setResearch(await researchQuestion(prompt) as SmartResearch)}catch(error){setResearch({error:error instanceof Error?error.message:'Research failed'})}finally{setResearching(false)}}
 return <main className="shell"><h1>LeadPilot AI · Lead Finder</h1><p>Find source-backed businesses, score them and inspect evidence. Trend signals are research evidence, not business leads.</p><section className="panel"><h2>Smart search</h2><form onSubmit={submit}><input value={prompt} onChange={e=>setPrompt(e.target.value)} placeholder="Try: salons in Lagos that need websites"/><div><button disabled={loading}>{loading?'Searching…':'Search businesses'}</button><button type="button" disabled={researching} onClick={researchNow}>{researching?'Researching…':'Deep research'}</button></div></form><label className="toggle"><input type="checkbox" checked={trendMode} onChange={e=>setTrendMode(e.target.checked)}/> Include trending discussion/news evidence</label>{research.error&&<p className="error">{research.error}</p>}{research.answer&&<div className="research"><b>AI synthesis</b><p>{research.answer}</p></div>}{research.sources?.length?<section><h3>Research sources</h3>{research.sources.map((s,i)=><p key={i}><a href={s.url} target="_blank" rel="noreferrer">{s.title}</a> · {s.source} · evidence {s.evidenceScore??0}/100</p>)}</section>:null}</section><section className="panel"><details><summary>Advanced filters</summary><div className="filters">{(['industry','country','city','keywords'] as const).map(k=><input key={k} value={filters[k]} placeholder={k} onChange={e=>setFilters({...filters,[k]:e.target.value})}/>)}</div></details><div className="legend"><LeadQualityBadge score={85}/><LeadQualityBadge score={55}/><LeadQualityBadge score={25}/><span>Good · Medium · Bad</span></div>{result.error&&<p className="error">{result.error}</p>}{trendMode&&result.trends?.length?<section className="trends"><h2>Trending signals — discussion/news evidence, not businesses</h2>{result.trends.map((t,i)=><article key={i}><b>{t.title}</b><p>{t.source}{t.community?` · ${t.community}`:''} · relevance {t.relevance}/100</p>{t.url&&<a href={t.url} target="_blank" rel="noreferrer">View signal</a>}</article>)}</section>:null}<h2>{result.count??result.results?.length??0} business leads</h2><div className="leads">{(result.results??[]).map((item,i)=>{const b=item.business??{};return <article key={item.lead?.id??i}><div className="row"><h3>{b.name??'Unknown business'}</h3><LeadQualityBadge score={item.lead?.score}/></div><p>{b.industry??'Industry not listed'} · {[b.city,b.country].filter(Boolean).join(', ')||'Location not listed'}</p><p>{item.report?.level??'Pending'} · {item.report?.confidence??0}% confidence</p><BusinessLink name={b.name??'business'} address={b.address} city={b.city} country={b.country} website={b.website}/></article>})}</div>{result.warnings?.length?<p className="muted">{result.warnings.join(' · ')}</p>:null}</section></main>;
}
