import type { LeadProvider } from '../providers/lead-provider';
import { createOutreachDraft, type OutreachDraft } from './outreach';
import { canSendOutreach } from './outreach-guard';
import { runGbpAudit, type GbpAudit } from './gbp-audit';
import { runPythonAgent } from './python-worker';
import type { AgentRunInput } from './runtime';
export interface GbpOutreachDraft extends OutreachDraft{leadId?:string;businessName:string;email?:string;eligible:boolean;eligibilityReason:string;issues:string[];approvalRequired:true}
function issueSummary(audit:GbpAudit){return audit.issues.map(issue=>`${issue.title}: ${issue.evidence}`).join(' ')}
export async function runGbpOutreach(accountId:string,providers:LeadProvider[],query:{keywords?:string;industry?:string;country?:string;city?:string;limit?:number}):Promise<{drafts:GbpOutreachDraft[];audits:GbpAudit[];warnings:string[];strategy:string[]}>{const {audits,warnings}=await runGbpAudit(accountId,providers,query);const fallback=(audit:GbpAudit)=>createOutreachDraft({company:audit.business.name,industry:audit.business.industry,location:[audit.business.city,audit.business.country].filter(Boolean).join(', '),website:audit.business.website,email:audit.business.email,painPoint:audit.issues.map(issue=>issue.title).join(', '),evidence:issueSummary(audit)},'Google Business Profile and local listing improvements');const python=await runPythonAgent({agent:'gbp-outreach',query:query.keywords||'Google Business Profile outreach',location:query.city,industry:query.industry,country:query.country,limit:query.limit} as AgentRunInput,{audits,businesses:audits.map(a=>a.business),issues:audits.map(a=>a.issues)});const drafts=audits.map((audit,index)=>{const guard=canSendOutreach({email:audit.business.email,phone:audit.business.phone,optedOut:false});const reasoning=python?.results[index] as Record<string,unknown>|undefined;const base=fallback(audit);const draft=reasoning&&typeof reasoning.draft==='string'?{...base,body:reasoning.draft}:reasoning&&typeof reasoning.subject==='string'&&typeof reasoning.body==='string'?{...base,subject:reasoning.subject,body:reasoning.body,followUp:typeof reasoning.followUp==='string'?reasoning.followUp:base.followUp,personalization:typeof reasoning.personalization==='string'?reasoning.personalization:base.personalization}:base;return{...draft,leadId:audit.leadId,businessName:audit.business.name,email:audit.business.email,eligible:guard.allowed,eligibilityReason:guard.reason,issues:audit.issues.map(issue=>issue.title),approvalRequired:true as const}});return{drafts,audits,warnings,strategy:['TypeScript owns GBP discovery, audit evidence, contact eligibility and approval/send enforcement.','Python owns personalized GBP outreach reasoning and drafting.','If Python is unavailable, TypeScript uses the safe deterministic draft fallback; nothing is sent automatically.']}}
