import type { AgentRunInput, AgentRunResult } from './runtime';
import { handleLeadFinder } from '../api/lead-finder-handler';
import { configuredLeadProviders } from '../providers/configured-provider';
import { runPythonAgent } from './python-worker';

const PYTHON_AGENT_URL = process.env.PYTHON_AGENT_URL?.replace(/\/$/, '');
const ROUTES: Record<string,string>={lead:'lead-finder',leads:'lead-finder',leadfinder:'lead-finder',trend:'trend-finder',trends:'trend-finder',opportunity:'opportunity-finder',opportunities:'opportunity-finder',tender:'tender-finder',tenders:'tender-finder',ecommerce:'ecommerce-opportunity',shop:'ecommerce-opportunity',work:'workpilot',content:'content',website:'website-brand',brand:'website-brand',competitor:'competitor-monitor',outreach:'outreach','gbp-audit':'gbp-audit','gbp-outreach':'gbp-outreach','gbp-fix':'gbp-fix'};
function chooseAgents(query:string):string[]{const q=query.toLowerCase();const out=new Set<string>();if(/competitor|competition|rival/.test(q))out.add(ROUTES.competitor);if(/trend|trending|hot|growing/.test(q))out.add(ROUTES.trend);if(/tender|procurement|bid|contract/.test(q))out.add(ROUTES.tender);if(/e-?commerce|product|sell online/.test(q))out.add(ROUTES.ecommerce);if(/website|brand|landing page|rebrand/.test(q))out.add(ROUTES.website);if(/content|post|copy|blog|caption/.test(q))out.add(ROUTES.content);if(/outreach|email|message prospects|contact prospects/.test(q))out.add(ROUTES.outreach);if(/google business|gbp|google profile|maps profile/.test(q))out.add(ROUTES['gbp-audit']);if(/workpilot|freelance|job|work opportunity/.test(q))out.add(ROUTES.work);if(/opportunit|market research|business idea/.test(q))out.add(ROUTES.opportunity);if(/lead|business|company|restaurant|customer|prospect|find .* in /.test(q))out.add(ROUTES.lead);return [...out].slice(0,3);}
async function synthesize(input:AgentRunInput,agents:string[],results:unknown[]):Promise<AgentRunResult>{if(!PYTHON_AGENT_URL)return{status:503,body:{error:'General Manager is not configured: PYTHON_AGENT_URL is missing.'}};const r=await fetch(`${PYTHON_AGENT_URL}/v1/agents/general-manager`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({query:input.query,location:input.location,city:input.city,country:input.country,industry:input.industry,limit:input.limit??25,agents,results}),signal:AbortSignal.timeout(30000)});const data=await r.json().catch(()=>({}));return r.ok?data as AgentRunResult:{status:r.status,body:data.error?data:{error:'General Manager synthesis failed.'}};}
export async function runGeneralManager(account:{accountId:string}|null,input:AgentRunInput):Promise<AgentRunResult>{const agents=chooseAgents(input.query);const selected=agents.length?agents:['lead-finder'];const results:unknown[]=[];for(const agent of selected){if(agent==='lead-finder'){const q={keywords:input.query,industry:input.industry,country:input.country,city:input.city||input.location,limit:input.limit??25};const r=await handleLeadFinder(account,q,configuredLeadProviders());const body=r.body as Record<string,unknown>;results.push({agent,results:Array.isArray(body.results)?body.results:[],warnings:Array.isArray(body.warnings)?body.warnings:[]});}else{const r=await runPythonAgent({...input,agent:agent as AgentRunInput['agent']});if(r)results.push({agent,results:r.results,warnings:r.warnings});}}
return synthesize(input,selected,results);}
