export type Lead = { id:string; name:string; category?:string; address?:string; city?:string; country?:string; latitude?:number; longitude?:number; source:string; sourceId?:string; website?:string; phone?:string; email?:string; tags?:Record<string,string>; score?:number };

type NominatimResult = { place_id?:number; osm_type?:string; osm_id?:number; display_name?:string; lat?:string; lon?:string; type?:string; category?:string; address?:Record<string,string>; extratags?:Record<string,string> };
const NOMINATIM='https://nominatim.openstreetmap.org/search';
const OVERPASS='https://overpass-api.de/api/interpreter';
function normalizeName(value:string){return value.toLowerCase().replace(/[^a-z0-9]+/g,' ').trim();}
function firstTag(tags:Record<string,string>|undefined,...keys:string[]){for(const key of keys){const value=tags?.[key]?.trim();if(value)return value;}return undefined;}
function mapResult(r:NominatimResult):Lead{const a=r.address||{};const tags=r.extratags||{};const id=`osm:${r.osm_type||'place'}:${r.osm_id||r.place_id||normalizeName(r.display_name||'unknown')}`;return {id,name:(tags.name||r.display_name||'Unknown business').split(',')[0],category:r.type||r.category,address:r.display_name,city:a.city||a.town||a.municipality||a.village,country:a.country,latitude:r.lat?Number(r.lat):undefined,longitude:r.lon?Number(r.lon):undefined,source:'openstreetmap',sourceId:id,website:firstTag(tags,'website','contact:website','url'),phone:firstTag(tags,'phone','contact:phone','mobile'),email:firstTag(tags,'email','contact:email'),tags};}
export async function discoverWithNominatim(query:string,limit=20):Promise<Lead[]>{const q=query.trim()||'business';const url=`${NOMINATIM}?q=${encodeURIComponent(q)}&format=jsonv2&addressdetails=1&extratags=1&limit=${Math.min(Math.max(limit,1),50)}`;const res=await fetch(url,{headers:{'User-Agent':'VictoryAI Lead Discovery/1.0'}});if(!res.ok)throw new Error(`Nominatim search failed: ${res.status}`);return ((await res.json()) as NominatimResult[]).map(mapResult);}
export async function discoverWithOverpass(query:string,limit=50):Promise<Lead[]>{const terms=query.trim().split(/\s+/).filter(Boolean).slice(0,8);const regex=terms.length?terms.map(t=>t.replace(/[.*+?^${}()|[\\]\\]/g,'\\$&')).join('|'):'.+';const q=`[out:json][timeout:15];(nwr["name"~"${regex}",i];nwr["brand"~"${regex}",i];);out center tags ${Math.min(Math.max(limit,1),100)};`;const res=await fetch(OVERPASS,{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded','User-Agent':'VictoryAI Lead Discovery/1.0'},body:`data=${encodeURIComponent(q)}`});if(!res.ok)throw new Error(`Overpass search failed: ${res.status}`);const data=await res.json() as {elements?:any[]};return (data.elements||[]).map((e:any)=>{const tags=e.tags||{};const lat=e.lat??e.center?.lat;const lon=e.lon??e.center?.lon;return {id:`osm:${e.type}:${e.id}`,name:tags.name||tags.brand||'Unnamed business',category:tags.shop||tags.amenity||tags.office||tags.tourism,address:[tags['addr:housenumber'],tags['addr:street'],tags['addr:city']].filter(Boolean).join(' ')||undefined,city:tags['addr:city'],country:tags['addr:country'],latitude:lat,longitude:lon,source:'openstreetmap-overpass',sourceId:`${e.type}:${e.id}`,website:firstTag(tags,'website','contact:website','url'),phone:firstTag(tags,'phone','contact:phone','mobile'),email:firstTag(tags,'email','contact:email'),tags};});}
export function mergeAndRank(leads:Lead[],limit=50){const seen=new Set<string>();return leads.filter(l=>{const key=normalizeName(`${l.name}|${l.city||''}|${l.country||''}`);if(seen.has(key))return false;seen.add(key);return true;}).map(l=>({...l,score:scoreLead(l)})).sort((a,b)=>(b.score||0)-(a.score||0)).slice(0,limit);}
function scoreLead(l:Lead){let s=40;if(l.website)s+=20;if(l.phone)s+=10;if(l.email)s+=10;if(l.city)s+=5;if(l.country)s+=5;if(l.category)s+=5;if(l.name&&l.name!=='Unnamed business')s+=10;return Math.min(s,100);}
export async function discoverLeads(query:string,limit=50){const [n,o]=await Promise.allSettled([discoverWithNominatim(query,Math.min(limit,20)),discoverWithOverpass(query,Math.min(limit,50))]);const leads=[...(n.status==='fulfilled'?n.value:[]),...(o.status==='fulfilled'?o.value:[])];if(!leads.length)throw new Error('No discovery source returned results. Try a broader business, niche, or location query.');return mergeAndRank(leads,limit);}
