import type { AgentRunInput } from './runtime';
import { selectDesign, buildHumanCopy, HUMAN_COPY_RULES } from './design-library';
import { humanize } from './collaboration';

type Block={id:string;type:string;variant?:string;props:Record<string,unknown>};
export type SiteConfig={name:string;designPattern:string;theme:{bg0:string;text0:string;accent:string;fontSans:string;fontDisplay:string;radius:number};blocks:Block[]};
function slug(s:string){return s.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,50)||'business-site';}
function infer(query:string){const q=query.toLowerCase(); if(/restaurant|food|cafe|bar|hotel/.test(q))return ['Hospitality']; if(/real estate|property|realtor/.test(q))return ['Professional Services']; if(/plumb|hvac|roof|contractor|construction|cleaning/.test(q))return ['Local Service']; if(/agency|marketing|photograph|design|beauty|fashion/.test(q))return ['Creative']; if(/saas|software|app|ai|tech/.test(q))return ['Software']; if(/school|church|nonprofit|community|fitness/.test(q))return ['Community']; return ['Business']; }
export function buildSite(query:string):SiteConfig{const pattern=selectDesign(query); const copy=buildHumanCopy(query,pattern); const [industry]=infer(query); return {name:query||industry,designPattern:pattern.id,theme:{bg0:'#09090b',text0:'#fafafa',accent:'#7c5cff',fontSans:'Inter',fontDisplay:'Space Grotesk',radius:12},blocks:[{id:'nav-1',type:'navbar',variant:'default',props:{logo:query||industry,links:pattern.sections.slice(1,5).map(x=>x.replace(/-/g,' ')),ctaText:copy.cta}},{id:'hero-1',type:'hero',variant:pattern.layout[0],props:{badge:pattern.personality.join(' · '),headline:humanize(copy.headline),subheadline:humanize(copy.subheadline),primaryCta:copy.cta}},{id:'services-1',type:'services',variant:'adaptive',props:{title:pattern.id==='hospitality'?'What’s on the menu':pattern.id==='software'?'What you can do':pattern.id==='commerce'?'What you’ll find':'How we can help',items:pattern.sections.slice(2,5).map((s,i)=>({title:s.replace(/-/g,' ').replace(/\b\w/g,m=>m.toUpperCase()),description:['Clear information about what you offer and who it is for.','Useful details that help people decide without a hard sell.','A straightforward next step when they are ready.'][i]||'Useful, specific information for your customers.'}))}},{id:'about-1',type:'about',variant:'story',props:{title:'A little more about us',description:`This section is intentionally written as a place for ${query||'the business owner'} to add the real story, experience and details that matter to customers. No invented claims.`}},{id:'faq-1',type:'faq',variant:'simple',props:{title:'Questions people usually ask',items:[{question:'How do I get started?',answer:'Tell us what you need and we’ll explain the next step.'},{question:'Where can I find the details?',answer:'Add your real contact, pricing, hours or service information here.'}]}},{id:'cta-1',type:'cta',variant:'centered',props:{title:pattern.id==='local-service'?'Need a hand?':'Have a question?',description:'Tell us what you need. We’ll make the next step clear.',buttonText:copy.cta}},{id:'footer-1',type:'footer',variant:'minimal',props:{copyright:`${query||industry} · Built with LeadPilot AI`}}]};}
function svgLogo(name:string){const n=(name||'LP').slice(0,2).toUpperCase();return `<svg xmlns="http://www.w3.org/2000/svg" width="1024" height="1024" viewBox="0 0 1024 1024"><rect width="1024" height="1024" rx="180" fill="#09090b"/><circle cx="512" cy="512" r="300" fill="#7c5cff"/><text x="512" y="570" text-anchor="middle" font-family="Arial,sans-serif" font-size="250" font-weight="700" fill="white">${n}</text></svg>`;}
async function generateLogo(name:string){const key=process.env.TOGETHER_API_KEY;if(!key)return {status:'fallback',format:'svg',svg:svgLogo(name),message:'A local logo is ready. Add TOGETHER_API_KEY when you want generative logo concepts.'}; const prompt=`Create a distinctive, friendly professional logo for ${name}. Make it feel human, memorable and simple enough to work as a small icon. Clean vector-like composition, no mockup, no watermark.`;try{const r=await fetch('https://api.together.xyz/v1/images/generations',{method:'POST',headers:{Authorization:`Bearer ${key}`,'Content-Type':'application/json'},body:JSON.stringify({model:'black-forest-labs/FLUX.1-schnell',prompt,n:1,width:1024,height:1024,response_format:'url'})});const d=await r.json();if(!r.ok)throw new Error(d?.error?.message||`Together API ${r.status}`);return {status:'generated',format:'image',url:d?.data?.[0]?.url,message:'Logo generated with Together AI.'};}catch(e){return {status:'fallback',format:'svg',svg:svgLogo(name),message:`Logo generation failed safely, so a local fallback was used: ${e instanceof Error?e.message:'unknown error'}`};}}
export async function runWebsiteBrand(input:AgentRunInput){const pattern=selectDesign(input.query);const site=buildSite(input.query);const logo=await generateLogo(site.name);return {agent:'website-brand',generatedAt:new Date().toISOString(),design:{pattern:pattern.id,personality:pattern.personality,layout:pattern.layout,tone:pattern.tone},copyRules:HUMAN_COPY_RULES,results:[{id:`site-${slug(site.name)}`,name:site.name,title:`Website + brand kit for ${site.name}`,description:'An original industry-aware website structure with human-first copy rules and editable content.',source:'LeadPilot Website & Brand Agent',websiteConfig:site,logo,score:92,lead:{score:92,scoreLabel:'GOOD',status:'ready'},url:`/api/website-brand?query=${encodeURIComponent(input.query)}`}],warnings:logo.status==='fallback'?[logo.message]:[],strategy:['Selects an industry-specific design pattern instead of one universal template.','Uses original page structure inspired by open design systems rather than copying a repository site.','Copy is customer-first, conversational and specific only where evidence supports it.','Unknown business facts are left for the owner instead of invented.','Logo generation uses Together AI when configured; otherwise a local SVG fallback is returned.','No generated code is claimed to be deployed until the user reviews and exports it.']};}
