import type { AgentRunInput } from './runtime';
import { humanize } from './collaboration';

type Block={id:string;type:string;variant?:string;props:Record<string,unknown>};
export type SiteConfig={name:string;theme:{bg0:string;text0:string;accent:string;fontSans:string;fontDisplay:string;radius:number};blocks:Block[]};

function slug(s:string){return s.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,50)||'business-site';}
function infer(query:string){const q=query.toLowerCase(); if(/restaurant|food|cafe|bar/.test(q))return ['Restaurant','Good food, a welcoming experience, and an easy way to book.']; if(/real estate|property|realtor/.test(q))return ['Real Estate','A clearer way to discover the right property.']; if(/plumb|hvac|roof|contractor|construction/.test(q))return ['Home Services','Reliable service, straightforward pricing, and a quick response.']; if(/agency|marketing/.test(q))return ['Creative Agency','Clear strategy, thoughtful creative work, and measurable growth.']; if(/saas|software|app|ai/.test(q))return ['Software','Explain the product clearly and give people a reason to try it.']; return ['Modern Business','A professional online presence built around real customers and real needs.']; }
export function buildSite(query:string):SiteConfig{const [industry,tag]=infer(query);return {name:query||industry,theme:{bg0:'#09090b',text0:'#fafafa',accent:'#7c5cff',fontSans:'Inter',fontDisplay:'Space Grotesk',radius:12},blocks:[{id:'nav-1',type:'navbar',variant:'default',props:{logo:industry,links:['Home','Services','About','Contact'],ctaText:'Let’s Talk'}},{id:'hero-1',type:'hero',variant:'centered',props:{badge:'A better first impression',headline:humanize(tag),subheadline:`A clear, welcoming website for ${query||industry}, written around what your customers actually need.`,primaryCta:'Let’s Talk'}},{id:'features-1',type:'features',variant:'grid',props:{title:'Why people choose us',items:[{icon:'Zap',title:'Quick to understand',description:'Visitors can see what you do and what to do next without digging.'},{icon:'Shield',title:'Built on trust',description:'Clear information, useful proof and a professional presentation.'},{icon:'Sparkles',title:'Easy to use',description:'A clean experience that feels natural on phones and larger screens.'}]}},{id:'cta-1',type:'cta',variant:'centered',props:{title:'Have a project in mind?',description:'Tell us what you need and we’ll figure out the next step together.',buttonText:'Get in touch'}},{id:'footer-1',type:'footer',variant:'minimal',props:{copyright:`${industry} · Built with LeadPilot AI`}}]};}
function svgLogo(name:string){const n=(name||'LP').slice(0,2).toUpperCase();return `<svg xmlns="http://www.w3.org/2000/svg" width="1024" height="1024" viewBox="0 0 1024 1024"><rect width="1024" height="1024" rx="180" fill="#09090b"/><circle cx="512" cy="512" r="300" fill="#7c5cff"/><text x="512" y="570" text-anchor="middle" font-family="Arial,sans-serif" font-size="250" font-weight="700" fill="white">${n}</text></svg>`;}
async function generateLogo(name:string){const key=process.env.TOGETHER_API_KEY;if(!key)return {status:'fallback',format:'svg',svg:svgLogo(name),message:'A local logo is ready. Add TOGETHER_API_KEY when you want generative logo concepts.'}; const prompt=`Create a distinctive, friendly professional logo for ${name}. Make it feel human, memorable and simple enough to work as a small icon. Clean vector-like composition, no mockup, no watermark.`;try{const r=await fetch('https://api.together.xyz/v1/images/generations',{method:'POST',headers:{Authorization:`Bearer ${key}`,'Content-Type':'application/json'},body:JSON.stringify({model:'black-forest-labs/FLUX.1-schnell',prompt,n:1,width:1024,height:1024,response_format:'url'})});const d=await r.json();if(!r.ok)throw new Error(d?.error?.message||`Together API ${r.status}`);return {status:'generated',format:'image',url:d?.data?.[0]?.url,message:'Logo generated with Together AI.'};}catch(e){return {status:'fallback',format:'svg',svg:svgLogo(name),message:`Logo generation failed safely, so a local fallback was used: ${e instanceof Error?e.message:'unknown error'}`};}}
export async function runWebsiteBrand(input:AgentRunInput){const site=buildSite(input.query);const logo=await generateLogo(site.name);return {agent:'website-brand',generatedAt:new Date().toISOString(),results:[{id:`site-${slug(site.name)}`,name:site.name,title:`Website + brand kit for ${site.name}`,description:'A human-readable website structure and brand asset that can be edited before export.',source:'LeadPilot Website & Brand Agent',websiteConfig:site,logo,score:92,lead:{score:92,scoreLabel:'GOOD',status:'ready'},url:`/api/website-brand?query=${encodeURIComponent(input.query)}`}],warnings:logo.status==='fallback'?[logo.message]:[],strategy:['Uses structured website data so agents can edit individual sections instead of rewriting an entire app.','Copy is intentionally conversational and avoids generic AI marketing language.','Logo generation uses Together AI when TOGETHER_API_KEY is configured; otherwise a local SVG fallback is returned.','No generated code is claimed to be deployed until the user reviews and exports it.']};}
